### ISSUE TITLE
Missing import: module cv2

### ISSUE THREAD

**Issue by wanbinkimoon** [Anve94/SudokuSolver#1]
When I try to execute your script it return this error.

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from ImagePrepper import ImagePrepper
  File "/Users/nicolabertelloni/Desktop/Demos/sodoku-demo/ImagePrepper.py", line 1, in <module>
    import cv2
ImportError: No module named cv2
```

 I digged in the files and found out that the module you try to import  in line 1 of `ImagePrepper` is missing in this repo.

**Comment by Anve94** [comment]
As mentioned in the readme file, the program requires some additional software in order to run properly. The very base of this program is a Computer Vision library called OpenCV. You need to install this locally on your system. On Linux-based systems, you can most likely install it with the python-opencv package.

For installation on different Operating Systems, you can find installation instructions on the [OpenCV documentation](http://docs.opencv.org/2.4/doc/tutorials/introduction/table_of_content_introduction/table_of_content_introduction.html).

Keep in mind that you will also need to install some other software, such as Google's tesseract. You can find the requirements in the readme file!
